const SERIE_A = [
  { id: "inter", name: "Inter Milan", color: "#003399" },
  { id: "juventus", name: "Juventus", color: "#000000" },
  { id: "milan", name: "AC Milan", color: "#FB090B" },
  { id: "napoli", name: "Napoli", color: "#12A0D7" },
  { id: "atalanta", name: "Atalanta", color: "#1E4597" },
  { id: "lazio", name: "Lazio", color: "#87CEEB" },
  { id: "roma", name: "AS Roma", color: "#8B0000" },
  { id: "fiorentina", name: "Fiorentina", color: "#5D2D91" },
  { id: "bologna", name: "Bologna", color: "#8B0000" },
  { id: "torino", name: "Torino FC", color: "#8B2500" },
  { id: "udinese", name: "Udinese", color: "#333333" },
  { id: "genoa", name: "Genoa CFC", color: "#CC0000" },
  { id: "monza", name: "AC Monza", color: "#CC0000" },
  { id: "lecce", name: "US Lecce", color: "#FFD700" },
  { id: "cagliari", name: "Cagliari", color: "#003399" },
  { id: "hellas", name: "Hellas Verona", color: "#FFD700" },
  { id: "empoli", name: "Empoli", color: "#0F7EC0" },
  { id: "como", name: "Como 1907", color: "#003399" },
  { id: "venezia", name: "Venezia FC", color: "#FF6600" },
  { id: "parma", name: "Parma Calcio", color: "#FFC72C" },
];

const PREMIER_LEAGUE = [
  { id: "arsenal", name: "Arsenal", color: "#EF0107" },
  { id: "liverpool", name: "Liverpool", color: "#C8102E" },
  { id: "man_city", name: "Manchester City", color: "#6CABDD" },
  { id: "man_utd", name: "Manchester United", color: "#DA291C" },
  { id: "chelsea", name: "Chelsea", color: "#034694" },
  { id: "spurs", name: "Tottenham Hotspur", color: "#132257" },
  { id: "newcastle", name: "Newcastle United", color: "#241F20" },
  { id: "aston_villa", name: "Aston Villa", color: "#670E36" },
  { id: "brighton", name: "Brighton", color: "#0057B8" },
  { id: "west_ham", name: "West Ham United", color: "#7A263A" },
  { id: "brentford", name: "Brentford", color: "#E30613" },
  { id: "crystal_palace", name: "Crystal Palace", color: "#1B458F" },
  { id: "fulham", name: "Fulham", color: "#CC0000" },
  { id: "wolves", name: "Wolverhampton", color: "#FDB913" },
  { id: "everton", name: "Everton", color: "#003399" },
  { id: "nottm_forest", name: "Nottingham Forest", color: "#DD0000" },
  { id: "bournemouth", name: "Bournemouth", color: "#DA291C" },
  { id: "leicester", name: "Leicester City", color: "#003090" },
  { id: "southampton", name: "Southampton", color: "#D71920" },
  { id: "ipswich", name: "Ipswich Town", color: "#003B80" },
];

const LA_LIGA = [
  { id: "real_madrid", name: "Real Madrid", color: "#FEBE10" },
  { id: "barcelona", name: "FC Barcelona", color: "#004D98" },
  { id: "atletico", name: "Atlético Madrid", color: "#CC0000" },
  { id: "athletic", name: "Athletic Club", color: "#EE2523" },
  { id: "villarreal", name: "Villarreal CF", color: "#FFE000" },
  { id: "real_sociedad", name: "Real Sociedad", color: "#003E96" },
  { id: "betis", name: "Real Betis", color: "#00954C" },
  { id: "sevilla", name: "Sevilla FC", color: "#D71A21" },
  { id: "celta", name: "Celta Vigo", color: "#8DB4E2" },
  { id: "osasuna", name: "Osasuna", color: "#D2000F" },
  { id: "girona", name: "Girona FC", color: "#CC0000" },
  { id: "rayo", name: "Rayo Vallecano", color: "#CC0000" },
  { id: "mallorca", name: "Mallorca", color: "#CC0000" },
  { id: "getafe", name: "Getafe CF", color: "#005FA8" },
  { id: "valencia", name: "Valencia CF", color: "#FF7F00" },
  { id: "espanol", name: "Espanyol", color: "#005898" },
  { id: "alaves", name: "Deportivo Alavés", color: "#1F549E" },
  { id: "valladolid", name: "Real Valladolid", color: "#6A0DAD" },
  { id: "laspalmas", name: "Las Palmas", color: "#FFDD00" },
  { id: "leganes", name: "Leganés", color: "#003C96" },
];

const BUNDESLIGA = [
  { id: "bmunich", name: "Bayern Munich", color: "#DC052D" },
  { id: "bayer_leverkusen", name: "Bayer Leverkusen", color: "#E32221" },
  { id: "rb_leipzig", name: "RB Leipzig", color: "#DD0741" },
  { id: "borussia_dortmund", name: "Borussia Dortmund", color: "#FDE100" },
  { id: "eintracht", name: "Eintracht Frankfurt", color: "#E1000F" },
  { id: "stuttgart", name: "VfB Stuttgart", color: "#E32221" },
  { id: "freiburg", name: "SC Freiburg", color: "#CC0000" },
  { id: "hoffenheim", name: "Hoffenheim", color: "#1663A7" },
  { id: "werder", name: "Werder Bremen", color: "#1D6F42" },
  { id: "wolfsburg", name: "VfL Wolfsburg", color: "#65B32E" },
  { id: "monchengladbach", name: "Borussia M'gladbach", color: "#000000" },
  { id: "augsburg", name: "FC Augsburg", color: "#BA3733" },
  { id: "union_berlin", name: "Union Berlin", color: "#CC0000" },
  { id: "mainz", name: "Mainz 05", color: "#CC0000" },
  { id: "heidenheim", name: "FC Heidenheim", color: "#CC0000" },
  { id: "bochum", name: "VfL Bochum", color: "#005CA9" },
  { id: "holstein_kiel", name: "Holstein Kiel", color: "#CC0000" },
  { id: "st_pauli", name: "St. Pauli", color: "#6F4F37" },
];

const LIGUE1_FR = [
  { id: "paris_sg", name: "Paris Saint-Germain", color: "#003399" },
  { id: "monaco", name: "AS Monaco", color: "#CC0000" },
  { id: "lille", name: "LOSC Lille", color: "#CC0000" },
  { id: "nice", name: "OGC Nice", color: "#CC0000" },
  { id: "marseille", name: "Olympique de Marseille", color: "#2FAEE0" },
  { id: "lyon", name: "Olympique Lyonnais", color: "#003399" },
  { id: "rennes", name: "Stade Rennais", color: "#CC0000" },
  { id: "lens", name: "RC Lens", color: "#FFCC00" },
  { id: "reims", name: "Stade de Reims", color: "#CC0000" },
  { id: "strasbourg", name: "RC Strasbourg", color: "#003399" },
  { id: "brest", name: "Stade Brestois", color: "#CC0000" },
  { id: "nantes", name: "FC Nantes", color: "#FFCC00" },
  { id: "toulouse", name: "Toulouse FC", color: "#6A0DAD" },
  { id: "montpellier", name: "Montpellier HSC", color: "#FF7C00" },
  { id: "auxerre", name: "AJ Auxerre", color: "#003399" },
  { id: "angers", name: "Angers SCO", color: "#000000" },
  { id: "saint_etienne", name: "AS Saint-Étienne", color: "#006633" },
  { id: "havre", name: "Le Havre AC", color: "#003F91" },
];

const LIGUE1_TUN = [
  { id: "est", name: "Espérance Sportive de Tunis", color: "#CC0000" },
  { id: "ca", name: "Club Africain", color: "#E30613" },
  { id: "ess", name: "Étoile Sportive du Sahel", color: "#B71C1C" },
  { id: "css", name: "Club Sportif Sfaxien", color: "#1A1A1A" },
  { id: "cab", name: "Club Athlétique Bizertin", color: "#CCAA00" },
  { id: "usm_tun", name: "US Monastir", color: "#003399" },
  { id: "st_tun", name: "Stade Tunisien", color: "#CC0000" },
  { id: "as_marsa", name: "AS Marsa", color: "#006600" },
  { id: "cs_hammam", name: "CS Hammam-Lif", color: "#CC0000" },
  { id: "ol_beja", name: "Olympique de Béja", color: "#FF6600" },
  { id: "as_soliman", name: "AS Soliman", color: "#003399" },
  { id: "us_tataouine", name: "US Tataouine", color: "#006600" },
  { id: "js_omrane", name: "JS Omrane", color: "#CC0000" },
  { id: "us_bengardane", name: "US Ben Guerdane", color: "#CC0000" },
];

const ALGERIE = [
  { id: "usma", name: "USM Alger", color: "#CC0000" },
  { id: "mca", name: "MC Alger", color: "#009A44" },
  { id: "crb", name: "CR Belouizdad", color: "#CC0000" },
  { id: "jsk", name: "JS Kabylie", color: "#FFCC00" },
  { id: "ess_setif", name: "ES Sétif", color: "#CC0000" },
  { id: "mco", name: "MC Oran", color: "#CC0000" },
  { id: "nahd", name: "NA Hussein Dey", color: "#CC0000" },
  { id: "cs_constantine", name: "CS Constantine", color: "#E55C00" },
  { id: "usb_alg", name: "US Biskra", color: "#006600" },
  { id: "paradou", name: "Paradou AC", color: "#003399" },
  { id: "aso_chlef", name: "ASO Chlef", color: "#CC0000" },
  { id: "hb_chelghoum", name: "HB Chelghoum Laïd", color: "#003399" },
  { id: "nc_magra", name: "NC Magra", color: "#003399" },
  { id: "usm_khenchela", name: "USM Khenchela", color: "#CC0000" },
  { id: "mc_eulma", name: "MC El Eulma", color: "#CC0000" },
  { id: "o_akbou", name: "O Akbou", color: "#CC0000" },
];

const MAROC = [
  { id: "wydad", name: "Wydad AC", color: "#CC0000" },
  { id: "raja", name: "Raja CA", color: "#006600" },
  { id: "rsb", name: "RS Berkane", color: "#FF8C00" },
  { id: "far_rabat", name: "FAR Rabat", color: "#006633" },
  { id: "fus_rabat", name: "FUS Rabat", color: "#003399" },
  { id: "hassania_agadir", name: "Hassania US Agadir", color: "#003399" },
  { id: "ittihad_tanger", name: "Ittihad Tanger", color: "#CC0000" },
  { id: "moghreb", name: "Moghreb Tétouan", color: "#003399" },
  { id: "maghreb_fes", name: "Maghreb de Fès", color: "#FF6B00" },
  { id: "kawkab", name: "Kawkab Marrakech", color: "#CC0000" },
  { id: "as_far", name: "AS FAR", color: "#006633" },
  { id: "olympic_khouribga", name: "Olympic Khouribga", color: "#003399" },
  { id: "chabab_moham", name: "Chabab Mohammedia", color: "#CC0000" },
  { id: "difaa_jadida", name: "Difaâ El Jadida", color: "#003399" },
];

const EGYPTE = [
  { id: "al_ahly", name: "Al Ahly SC", color: "#CC0000" },
  { id: "zamalek", name: "Zamalek SC", color: "#1A5276" },
  { id: "pyramids", name: "Pyramids FC", color: "#FFD700" },
  { id: "future_fc", name: "Future FC", color: "#003399" },
  { id: "ismaily", name: "Ismaily SC", color: "#FFCC00" },
  { id: "al_masry", name: "Al Masry", color: "#006600" },
  { id: "el_gaish", name: "El Gaish SC", color: "#CC0000" },
  { id: "arab_contractors", name: "Arab Contractors", color: "#CC0000" },
  { id: "ceramica", name: "Ceramica Cleopatra", color: "#003399" },
  { id: "ghazl_mahalla", name: "Ghazl El Mahalla", color: "#CC0000" },
  { id: "el_ittihad_alex", name: "El Ittihad Alexandria", color: "#003399" },
  { id: "al_mokawloon", name: "Al Mokawloon", color: "#CC0000" },
  { id: "national_bank", name: "National Bank SC", color: "#003399" },
  { id: "haras_hodood", name: "Haras El Hodood", color: "#CC0000" },
];

const NATIONALES = [
  { id: "tunisie", name: "Équipe de Tunisie", color: "#CC0000" },
  { id: "algerie", name: "Équipe d'Algérie", color: "#006233" },
  { id: "maroc", name: "Équipe du Maroc", color: "#C1272D" },
  { id: "egypte", name: "Équipe d'Égypte", color: "#CC0001" },
  { id: "france_nat", name: "Équipe de France", color: "#003399" },
  { id: "italie_nat", name: "Équipe d'Italie", color: "#003399" },
  { id: "espagne_nat", name: "Équipe d'Espagne", color: "#CC0000" },
  { id: "allemagne_nat", name: "Équipe d'Allemagne", color: "#333333" },
  { id: "angleterre_nat", name: "Équipe d'Angleterre", color: "#CC0000" },
  { id: "portugal_nat", name: "Équipe du Portugal", color: "#006600" },
  { id: "bresil_nat", name: "Équipe du Brésil", color: "#009C3B" },
  { id: "argentine_nat", name: "Équipe d'Argentine", color: "#74ACDF" },
];

export const TEAMS_BY_GROUP = [
  { group: "Serie A", leagueId: "serie", teams: SERIE_A },
  { group: "Premier League", leagueId: "pl", teams: PREMIER_LEAGUE },
  { group: "La Liga", leagueId: "liga", teams: LA_LIGA },
  { group: "Bundesliga", leagueId: "bundesliga", teams: BUNDESLIGA },
  { group: "Ligue 1 (France)", leagueId: "ligue1fr", teams: LIGUE1_FR },
  { group: "Tunisie", leagueId: "ligue1", teams: LIGUE1_TUN },
  { group: "Algérie", leagueId: "algerie", teams: ALGERIE },
  { group: "Maroc", leagueId: "maroc", teams: MAROC },
  { group: "Égypte", leagueId: "egypte", teams: EGYPTE },
  { group: "Équipes nationales", leagueId: "national", teams: NATIONALES },
  { group: "Autre", leagueId: "autre", teams: [{ id: "autre", name: "Autre", color: "#888888" }] },
];

export const ALL_TEAMS = TEAMS_BY_GROUP.flatMap((g) =>
  g.teams.map((t) => ({ ...t, group: g.group }))
);

export function getTeam(id) {
  return ALL_TEAMS.find((t) => t.id === id);
}
